### ISSUE TITLE
Add Config option to only pull active contacts

### ISSUE THREAD

**Issue by briangig** [jundis/CWSlack-SlashCommands#101]
Some day I will figure out how to submit code changes...but today is not the day.  And for that I am sorry.

In config.php, add this to line 48:

`$returninactive = "False";`

in cwslack-contacts.php:

Replace Line 58 with:

`	$url = $connectwise . "/v4_6_release/apis/3.0/company/contacts?conditions=inactiveFlag=" . $returninactive . "%20and%20lastName%20like%20%27" . $lastname . "%27"; //Set contact API url`

Replace Line 65 with:

`	$url = $connectwise . "/v4_6_release/apis/3.0/company/contacts?conditions=inactiveFlag=" . $returninactive . "%20and%20lastName%20like%20%27" . $lastname . "%27%20and%20firstName%20like%20%27" . $firstname . "%27"; //Set contact API url to include first and last name.`

You can then set $returninactive to either True or False.

**Comment by jundis** [comment]
Thanks @briangig. Adjusted the code slightly so basic true/false values are accepted.
