### ISSUE TITLE
Incoming Tickets Issue

### ISSUE THREAD

**Issue by digitalbydesign** [jundis/CWSlack-SlashCommands#110]
I'm having an issue where I've set the boards I don't want to pull with cw-incoming but it continues to pull in tickets from those boards. Below is the code in my config file, am I doing something wrong? Any help would be appreciated as we have a "maintenance" board that auto-generates a lot of tickets from our RMM that I'd like to avoid seeing within Slack.

$badboard = "NOC Team" | "SALES" | "IT Projects - AZ" | "IT Projects - TX" | "MAINTENANCE."; //Set to any board name you want to fail, to avoid ticket creation/updates from this board posting to Slack.

**Comment by jundis** [comment]
Try the one below instead. Just 1 set of quotes, seperated inside by pipes.

`$badboard = "NOC Team|SALES|IT Projects - AZ|IT Projects - TX|MAINTENANCE";`

Keep in mind names must be exact, including case.

**Comment by digitalbydesign** [comment]
This still didn't work unfortunately. Any other ideas?

**Comment by jundis** [comment]
See the comment here: https://github.com/jundis/CWSlack-SlashCommands/issues/41#issuecomment-257712965

Do that but change the board name in the data.txt block to "MAINTENANCE" from "Not" then execute the command. If that posts to slack, then do the code changes below and repeat the command.

Line 46 ADD: 
`echo $info->BoardName;
var_dump($badboards);
die("Testing");`

Let me know what the output is of that from the curl command.

**Comment by digitalbydesign** [comment]
I did the command referenced and it did not post to Slack. Output is below:

root@slack:/tmp# curl -d @data.txt -iv --raw -H "Content-Type:
application/json" "
https://slack.lutrum.com/cwslack-incoming.php?id=545137&action=added&srDetailRecId=1002946&timeRecId=0&srtServiceRecId=0&memberId=techname&notes=&isProblemDescription=True&isInternalAnalysis=False&isResolution=False
"
*   Trying 127.0.1.1...
* Connected to slack.lutrum.com (127.0.1.1) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 694 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: slack.lutrum.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=slack.lutrum.com
*        start date: Sat, 29 Apr 2017 20:36:00 GMT
*        expire date: Fri, 28 Jul 2017 20:36:00 GMT
*        issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
*        compression: NULL
* ALPN, server accepted to use http/1.1
> POST
/cwslack-incoming.php?id=545137&action=added&srDetailRecId=1002946&timeRecId=0&srtServiceRecId=0&memberId=techname&notes=&isProblemDescription=True&isInternalAnalysis=False&isResolution=False
HTTP/1.1
> Host: slack.lutrum.com
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 1271
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

* We are completely uploaded and fine
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Tue, 09 May 2017 13:03:15 GMT
Date: Tue, 09 May 2017 13:03:15 GMT
< Server: Apache/2.4.18 (Ubuntu)
Server: Apache/2.4.18 (Ubuntu)
< Content-Length: 113
Content-Length: 113
< Content-Type: application/json
Content-Type: application/json

<
* Connection #0 to host slack.lutrum.com left intact
No ticket data was submitted. This is expected behavior if you are just
browsing to this page with a web browser.



Do I still need to add that line of code and attempt the curl command again?


Thanks for your help!

**Comment by jundis** [comment]
Did you make sure the data.txt was in the same folder as you were running this command, in this case /tmp?

**Comment by digitalbydesign** [comment]
Yup.

**Comment by jundis** [comment]
Hm. Yea unfortunately I'm not 100% how to go from here as that curl command works fine on my instance of Ubuntu 14.04 LTS as well as the Bash vm on Windows 10.

The error provided there is on line 29 of cwslack-incoming.php and is only triggered when no data is submitted, in this case when the data.txt file is not actually posted.

**Comment by digitalbydesign** [comment]
Question, in reference to the data.txt file setup, I assume that I was
supposed to change all the information to reflect our environment,
i.e. "FromUrl":
"cw.you.com",
"CompanyId": "company", or was that supposed to be list as-is?

The output of the CURL command looks successful but I assume it's actually
SUPPOSED to post to Slack? Guess I'm confused.

Thanks,
Troy

**Comment by jundis** [comment]
Everything looks good up until the last part

`No ticket data was submitted. This is expected behavior if you are just
browsing to this page with a web browser.
`
That's only returned if the script doesn't see the data.txt information.

Try doing it with just the data.txt I had posted, without modification. Only the curl command needed modification

**Comment by digitalbydesign** [comment]
I made the changes back to the defaults from the post and I still get the
same output. Now, I'm not sure what version of CWSlack I'm running at this
point, I haven't updated in awhile.

Troy

**Comment by digitalbydesign** [comment]
I just did the update to 2.3 and modified the badboard line and now it
appears to be working. I definitely appreciate all your help.

Thanks,
Troy

**Comment by jundis** [comment]
Best advice then would be to scrap it all and start fresh on 2.4. You can
copy the values over from your current config, but start a new one of those
too.
