### ISSUE TITLE
Command for time entries doesn't seem to like the "h" shorthand

### ISSUE THREAD

**Issue by tfox-mi** [jundis/CWSlack-SlashCommands#112]
Hi. First things first: THIS IS AWESOME!!!

I'm having a little trouble with the /time command. I am unable to enter time in the format of "1.5h" but if i use "90m" it works fine.

Command I'm using:
/time 200572 r 1.5h ticket notes go here

Result in Slack:
Unknown Error Occurred, check API key and other API settings. Error InvalidObject: timeEntry object is invalid

If I use the command:
/time 200572 r 90m ticket notes go here

It works just fine.

I'm sure I have something not configured properly - hoping you can point me in the right direction.

Thank you again for your work on this integration. It is the bomb dot com.

Tom

**Comment by jundis** [comment]
It's a bug for sure. Happening for me as well. Are you on 2017.3 as well?

**Comment by jundis** [comment]
Was just a bug in my php code. Fixed in the latest commit so redownload cwslack-time.php and it will work fine.

**Comment by tfox-mi** [comment]
We're using 2017.4.47999 (Pilot). Thanks for the fix! Tom
