### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by mycotrip** [jundis/CWSlack-SlashCommands#113]
The integration is currently working and has been functioning perfectly for quite a while. Until recently only one user, my self, was really using the ticket creation/notation functionality. We now have another user that would like to use this functionality... The API Key for CW currently configured is from my CW acct. The only way I can see to make this work would be to recreate the file structure in a different path on the webserver and configure that file structure with the new users API Key from CW.. Is there something I am missing or would this be the only way to do it?

**Comment by jundis** [comment]
You need to use the dbmanage command to fix that. I copied the readme excerpt below, but effectively you just need to do /dbm addmap [slackname] [cwname] for each user and it should start working.

cwslack-dbmanage.php

/dbm [command]* [options]

Commands available:

help - Display this help text
listmap - List all username mappings between CW and Slack
addmap [slackname]* [cwname]* - Associate the two names
removemap [slackname]* - Remove a mapping
clearfollow confirm* - Clears the follow database

**Comment by mycotrip** [comment]
Thanks for the quick reply..... i totally forgot to add him to the db

**Comment by jundis** [comment]
No problem! Let me know if you need any other help
