### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by dsinton** [jundis/CWSlack-SlashCommands#116]
i recently upgraded from an older version maybe 2.0 tot he latest and i get the error below. i have reset api's and still have the same issue

Notice: Undefined property: stdClass::$text in /var/www/html/cwslack.php on line 625

Unknown Error Occurred, check API key and other API settings. Error ApiFindCondition: Condition Syntax Error (Line 1, Character 9) - Unrecognized value: 4ANDobjectId
String values should be enclosed with double or single quotes; DateTime values should be enclosed in square brackets; numbers should consist of only digits, and optionally a decimal point and a negation sign; boolean values should be indicated with the keywords true or false; null values should be indicated by the keyword null.

**Comment by jundis** [comment]
Can you please set $debugmode to true in config.php, try the same command again, then sanitize the output by removing sensitive info and paste it here?

**Comment by dsinton** [comment]
CWbot APP [4:06 PM] Only visible to you
string(5129) "HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 4678
Connection: keep-alive
Date: Tue, 15 Aug 2017 20:06:44 GMT
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 50ce79d11488558ae66a3f9bac6f0faa.cloudfront.net (CloudFront)
X-Amz-Cf-Id: N5G04dgxI8Q99dmUKqfc82gMXc81LpvwUTO71inrg4dEFOhYhm6xuw==

{"id":354475,"summary":"CW slack integration","recordType":"ServiceTicket","board":{"id":21,"name":"Central Services","_info":{"board_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/boards/21"}},"status":{"id":601,"name":"Waiting on Vendor","_info":{"status_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/boards/21/statuses/601"}},"company":{"id":2,"identifier":"company Corporation","name":"company Corporation","_info":{"company_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/companies/2","mobileGuid":"b708abcb-5fae-4eba-9f11-f1d39b2b5a1d"}},"site":{"id":136,"name":"cityname (HQ)","_info":{"site_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/companies/2/sites/136","mobileGuid":"e8e095b4-2097-4bf1-98fa-d446ae252823"}},"siteName":"cityname (HQ)","addressLine1":"26 streetname Rd","city":"cityname","stateIdentifier":"NJ","zip":"zipcode","country":{"id":1,"name":"United States"},"contact":{"id":188,"name":"first2 last2","_info":{"mobileGuid":"fbbf5dab-d6e4-466c-9081-e6b3ceea592a","contact_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/contacts/188"}},"contactName":"first2 last2","contactPhoneNumber":"1234567890","contactPhoneExtension":"155","contactEmailAddress":"flast2@companycorp.com","type":{"id":327,"name":"Tools","_info":{"type_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/boards/21/types/327"}},"team":{"id":43,"name":"CS","_info":{"team_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/boards/21/teams/43"}},"owner":{"id":207,"identifier":"flast","name":"first1 last","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207","image_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207/image?lm=2017-03-28T14:01:47Z"}},"priority":{"id":6,"name":"Priority 4","sort":4,"_info":{"priority_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/priorities/6","image_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/priorities/6/image?lm=2011-04-20T17:52:27Z"}},"serviceLocation":{"id":2,"name":"In-House at company","_info":{"location_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/locations/2"}},"source":{"id":2,"name":"Phone","_info":{"source_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/sources/2"}},"severity":"Low","impact":"Low","allowAllClientsPortalView":false,"customerUpdatedFlag":false,"automaticEmailContactFlag":false,"automaticEmailResourceFlag":false,"automaticEmailCcFlag":false,"closedFlag":false,"dateEntered":"2016-09-19T15:13:03Z","enteredBy":"flast","actualHours":5.50,"approved":true,"subBillingMethod":"ActualRates","dateResponded":"2016-09-20T13:56:38Z","resolveMinutes":0,"resPlanMinutes":0,"respondMinutes":463,"isInSla":false,"resources":"flast","hasChildTicket":false,"billTime":"NoDefault","billExpenses":"NoDefault","billProducts":"DoNotBill","locationId":2,"businessUnitId":10,"mobileGuid":"609b0760-bea2-4b17-8079-97a0315ce05e","sla":{"id":6,"name":"Default SLA","_info":{"sla_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/SLAs/6"}},"currency":{"id":7,"symbol":"$","isoCode":"USD","name":"US Dollars","_info":{"currency_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/finance/currencies/7"}},"_info":{"lastUpdated":"2017-08-14T18:56:35Z","updatedBy":"flast","activities_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/sales/activities?conditions=ticket/id=354475","scheduleentries_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/schedule/entries?conditions=type/id=4 AND objectId=354475","documents_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/documents?recordType=Ticket&recordId=354475","configurations_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/tickets/354475/configurations","tasks_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/tickets/354475/tasks","notes_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/service/tickets/354475/notes","products_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/procurement/products?conditions=chargeToType='Ticket' AND chargeToId=354475","timeentries_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/entries?conditions=(chargeToType='ServiceTicket' OR chargeToType='ProjectTicket') AND chargeToId=354475","expenseEntries_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/expense/entries?conditions=(chargeToType='ServiceTicket' OR chargeToType='ProjectTicket') AND chargeToId=354475"}}"
string(1410) "HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 983
Connection: keep-alive
Date: Tue, 15 Aug 2017 20:06:45 GMT
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
X-Cache: Miss from cloudfront
Via: 1.1 b2566c33186e0b7da4759cb2082b0f5d.cloudfront.net (CloudFront)
X-Amz-Cf-Id: xWwX16ferca1779No8U15Qwl5Y4R0BO77hOhCIgKTMdRnSOoHyacEg==

[{"id":798063,"ticketId":354475,"text":"Updated / flast / ","detailDescriptionFlag":false,"internalAnalysisFlag":true,"resolutionFlag":false,"member":{"id":202,"identifier":"flast2","name":"first2 last2","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/202"}},"dateCreated":"2017-07-19T20:21:15Z","createdBy":"flast2","internalFlag":true,"externalFlag":false,"_info":{"lastUpdated":"2017-07-19T20:21:15Z","updatedBy":"flast2"}},{"id":737005,"ticketId":354475,"text":"https://github.com/jundis/CWSlack-SlashCommands","detailDescriptionFlag":true,"internalAnalysisFlag":false,"resolutionFlag":false,"member":{"id":207,"identifier":"flast","name":"first1 last","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207"}},"dateCreated":"2016-09-19T15:13:03Z","createdBy":"flast","internalFlag":true,"externalFlag":false,"_info":{"lastUpdated":"2016-09-19T15:13:03Z","updatedBy":"flast"}}]"
string(9803) "HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 9352
Connection: keep-alive
Date: Tue, 15 Aug 2017 20:06:45 GMT
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 9fab2a39c6d2bda91a3a58e2e1e6133d.cloudfront.net (CloudFront)
X-Amz-Cf-Id: mJjSkm6oAd49s-TCyUrDgwVBoVr78JG54ltuLWHd4BGjtJ-5aMh2Tg==

[{"id":297883,"company":{"id":2,"identifier":"company Corporation","name":"company Corporation","_info":{"company_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/companies/2","mobileGuid":"b708abcb-5fae-4eba-9f11-f1d39b2b5a1d"}},"chargeToId":354475,"chargeToType":"ServiceTicket","member":{"id":207,"identifier":"flast","name":"first1 last","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207"}},"locationId":2,"businessUnitId":10,"workType":{"id":3,"name":"Professional Services","_info":{"workType_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/workTypes/3"}},"workRole":{"id":11,"name":"Engineer","_info":{"workRole_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/workRoles/11"}},"timeStart":"2017-08-14T17:30:00Z","timeEnd":"2017-08-14T19:00:00Z","hoursDeduct":0.00,"actualHours":1.50,"billableOption":"Billable","notes":"- upgraded to latest version 2.4?\n- erro, reconfigured config.php, uploaded new cwslack and function\nreset api's\nreache dout to dev\n\n\npending:  hope dev is able to fix for me\n\nerror\n<br />\n<b>Notice</b>:  Undefined property: stdClass::$text in <b>/var/www/html/cwslack.php</b> on line <b>625</b><br />\nUnknown Error Occurred, check API key and other API settings. Error ApiFcompanyCondition: Condition Syntax Error (Line 1, Character 9) - Unrecognized value: 4ANDobjectId\nString values should be enclosed with double or single quotes; DateTime values should be enclosed in square brackets; numbers should consist of only digits, and optionally a decimal point and a negation sign; boolean values should be companyicated with the keywords true or false; null values should be companyicated by the keyword null.","addToDetailDescriptionFlag":true,"addToInternalAnalysisFlag":false,"addToResolutionFlag":false,"emailResourceFlag":false,"emailContactFlag":false,"emailCcFlag":false,"hoursBilled":1.50,"enteredBy":"flast","dateEntered":"2017-08-14T18:56:00Z","mobileGuid":"2ad7282e-fea8-4155-a0b5-8ac2b5431390","hourlyRate":175.0000,"timeSheet":{"id":8237,"name":"2017-08-12 to 2017-08-18","_info":{"timeSheet_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/sheets/8237"}},"status":"Open","_info":{"lastUpdated":"2017-08-14T18:56:00Z","updatedBy":"flast","chargeToMobileGuid":"609b0760-bea2-4b17-8079-97a0315ce05e"}},{"id":262671,"company":{"id":2,"identifier":"company Corporation","name":"company Corporation","_info":{"company_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/companies/2","mobileGuid":"b708abcb-5fae-4eba-9f11-f1d39b2b5a1d"}},"chargeToId":354475,"chargeToType":"ServiceTicket","member":{"id":207,"identifier":"flast","name":"first1 last","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207"}},"locationId":2,"businessUnitId":10,"workType":{"id":3,"name":"Professional Services","_info":{"workType_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/workTypes/3"}},"workRole":{"id":11,"name":"Engineer","_info":{"workRole_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/workRoles/11"}},"timeStart":"2016-12-13T21:29:00Z","timeEnd":"2016-12-13T21:44:00Z","hoursDeduct":0.00,"actualHours":0.25,"billableOption":"Billable","notes":"new veruison available\npending:  update and implemnt","addToDetailDescriptionFlag":true,"addToInternalAnalysisFlag":false,"addToResolutionFlag":false,"emailResourceFlag":false,"emailContactFlag":false,"emailCcFlag":false,"hoursBilled":0.25,"enteredBy":"flast","dateEntered":"2016-12-13T21:33:05Z","mobileGuid":"cb262a99-2ee9-432a-a807-f85666f9f7f0","hourlyRate":175.0000,"timeSheet":{"id":7147,"name":"2016-12-10 to 2016-12-16","_info":{"timeSheet_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/sheets/7147"}},"status":"WrittenOff","_info":{"lastUpdated":"2016-12-29T16:46:12Z","updatedBy":"flast2","chargeToMobileGuid":"609b0760-bea2-4b17-8079-97a0315ce05e"}},{"id":253523,"company":{"id":2,"identifier":"company Corporation","name":"company Corporation","_info":{"company_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/companies/2","mobileGuid":"b708abcb-5fae-4eba-9f11-f1d39b2b5a1d"}},"chargeToId":354475,"chargeToType":"ServiceTicket","member":{"id":207,"identifier":"flast","name":"first1 last","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207"}},"locationId":2,"businessUnitId":10,"workType":{"id":3,"name":"Professional Services","_info":{"workType_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/workTypes/3"}},"workRole":{"id":11,"name":"Engineer","_info":{"workRole_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/workRoles/11"}},"timeStart":"2016-10-04T19:09:00Z","timeEnd":"2016-10-04T19:54:00Z","actualHours":0.75,"billableOption":"Billable","notes":"updated to latest version1.7 same issue\n troubleshot and found issu was curl install php7.0-curl and restarte apache and now working\n\npending:  test and lock down","addToDetailDescriptionFlag":true,"addToInternalAnalysisFlag":false,"addToResolutionFlag":false,"emailResourceFlag":false,"emailContactFlag":false,"emailCcFlag":false,"hoursBilled":0.75,"enteredBy":"flast","dateEntered":"2016-10-04T19:39:44Z","mobileGuid":"beaf73ab-46e8-44cb-8967-16a9d97b3382","hourlyRate":175.0000,"timeSheet":{"id":6965,"name":"2016-10-01 to 2016-10-07","_info":{"timeSheet_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/sheets/6965"}},"status":"WrittenOff","_info":{"lastUpdated":"2016-10-14T12:51:56Z","updatedBy":"flast2","chargeToMobileGuid":"609b0760-bea2-4b17-8079-97a0315ce05e"}},{"id":251671,"company":{"id":2,"identifier":"company Corporation","name":"company Corporation","_info":{"company_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/companies/2","mobileGuid":"b708abcb-5fae-4eba-9f11-f1d39b2b5a1d"}},"chargeToId":354475,"chargeToType":"ServiceTicket","member":{"id":207,"identifier":"flast","name":"first1 last","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207"}},"locationId":2,"businessUnitId":10,"workType":{"id":3,"name":"Professional Services","_info":{"workType_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/workTypes/3"}},"workRole":{"id":11,"name":"Engineer","_info":{"workRole_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/workRoles/11"}},"timeStart":"2016-09-20T17:00:00Z","timeEnd":"2016-09-20T19:00:00Z","actualHours":2.00,"billableOption":"Billable","notes":"- setup api''s and copied configs but no response, was able to get some erros resolved but still not working, current error\n\n]\n<br />\n<b>Fatal error</b>:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/cwslack.php:76\nStack trace:\n#0 {main}\n thrown in <b>/var/www/html/cwslack.php</b> on line <b>76</b><br />\n\npending:  continue to troubleshoot","addToDetailDescriptionFlag":true,"addToInternalAnalysisFlag":false,"addToResolutionFlag":false,"emailResourceFlag":false,"emailContactFlag":false,"emailCcFlag":false,"hoursBilled":2.00,"enteredBy":"flast","dateEntered":"2016-09-20T19:44:36Z","mobileGuid":"d5935edc-5689-4158-9e3f-c8dd39bd3016","hourlyRate":175.0000,"timeSheet":{"id":6917,"name":"2016-09-17 to 2016-09-23","_info":{"timeSheet_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/sheets/6917"}},"status":"WrittenOff","_info":{"lastUpdated":"2016-09-30T11:19:38Z","updatedBy":"flast2","chargeToMobileGuid":"609b0760-bea2-4b17-8079-97a0315ce05e"}},{"id":251564,"company":{"id":2,"identifier":"company Corporation","name":"company Corporation","_info":{"company_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/company/companies/2","mobileGuid":"b708abcb-5fae-4eba-9f11-f1d39b2b5a1d"}},"chargeToId":354475,"chargeToType":"ServiceTicket","member":{"id":207,"identifier":"flast","name":"first1 last","_info":{"member_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/members/207"}},"locationId":2,"businessUnitId":10,"workType":{"id":3,"name":"Professional Services","_info":{"workType_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/system/workTypes/3"}},"workRole":{"id":11,"name":"Engineer","_info":{"workRole_href":"https://api-na.myconnectwise.net/v4_6_release/apis/3.0/time/workRoles/11"}},"timeStart":"2016-09-20T12:30:00Z","timeEnd":"2016-09-20T13:30:00Z","actualHours":1.00,"billableOption":"Billable","notes":"- downloaded ubuntu server\n- installe din hyper v on my p (will move to server if works well)\n- installe dLAMP on server and tested\n\npending:  copy configs over and test on test slack account","addToDetailDescriptionFlag":true,"addToInternalAnalysisFlag":false,"addToResolutionFlag":false,"emailResourceFlag":false,"emailContactFlag":false,"emailCcFlag":false,"hoursBilled":1.00,"enteredBy":"flast","dateEntered":"2016-09-20T13:56:47

**Comment by jundis** [comment]
Sorry for the delay in responding. Are you on v2017.4 for ConnectWise or are you on an earlier version?

**Comment by dsinton** [comment]
We are on a newer version. 2017_5

**Comment by jundis** [comment]
Did you run through the upgrade scripts or did you do a clean config for this? If the latter I would advise doing a clean install again from the latest master files (not releases) here https://github.com/jundis/CWSlack-SlashCommands/archive/master.zip .

If you did do a clean install for this, then I would double check and make sure curl is installed as the more concerning error I'm seeing in the logs is:
`Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/cwslack.php:76  
Stack trace:  
#0 {main}  
 thrown in /var/www/html/cwslack.php on line 76`

which points to curl being an issue.

Make a phpinfo() page and drop it somewhere in your web folders, visit it in a browser and Ctrl+F curl and make sure its got a full block of information, and not just a single line.

https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page

**Comment by dsinton** [comment]
I did the upgrade not fresh install. Full php page works. I am going to
move to a new web server. You can close issue. I will make new one if I
have issues on the new server.
