### ISSUE TITLE
Contacts Wildcard Search

### ISSUE THREAD

**Issue by timjcraig** [jundis/CWSlack-SlashCommands#123]
Would it be possible to search contacts with wildcard search? For example cra* would return all contacts with last name beginning with cra. 

Thank you for the application.

**Comment by jundis** [comment]
Tim,

I'm closing this as I am no longer actively developing this open source version of CWSlack and further new feature development is going towards the hosted CWSlack v3 product, which details will be released about in the near future.

Additional work on this project will be on a bug-only basis.

Thanks,
Joey
