### ISSUE TITLE
/lunch command always thinks we already took a lunch

### ISSUE THREAD

**Issue by tfox-mi** [jundis/CWSlack-SlashCommands#124]
Hi we're using the /lunch command, and after the first day of use, the command always thinks we've already taken a lunch and gives us the "split lunch" message.

**Comment by jundis** [comment]
Please use the newly uploaded cwslack-lunch-cron.php and schedule it in your crontab, like priorityalerts and firmalerts, using

0 0 * * * 

to run it at midnight.
