### ISSUE TITLE
Issue selecting priorities in cwslack

### ISSUE THREAD

**Issue by tfox-mi** [jundis/CWSlack-SlashCommands#125]
Hi, no matter how I formatted the command, I was unable to get a ticket status to match. I reviewed the API documentation and added an asterisk before and after the search term, and now it is working properly. The updated line 258 from cwslack.php that works for our system is:

$priorityurl = $connectwise . "/$connectwisebranch/apis/3.0/service/priorities?conditions=name%20like%20%27%2A" . $option3 . "%2A%27";

Reference from the API:
https://developer.connectwise.com/Manage/Developer_Guide#Condition_Formatting

**Comment by jundis** [comment]
Thanks and sorry for the delay on this. Updated in the file!
