### ISSUE TITLE
Can't get incoming to work

### ISSUE THREAD

**Issue by briangig** [jundis/CWSlack-SlashCommands#127]
I can't seem to get incoming notifications working on a new 2.5 install.  I suspect the issue is on the CW end, but is there anyway to get some logs from the CWSlack end?  I am able to get notifications using curl and the commands suggested in issue #41

**Comment by jundis** [comment]
So notifications work when you use it through CURL but not when you create a new ticket in CW?

Unfortunately theres no logs for that, but it's likely related to your callback/integrator login setup in the CW setup tables.

Ensure that it has access to all records, not just ones that it creates, that it has service ticket checked but not legacy API, and that the URL is https://you.tld/cwslack-incoming.php?id= (?id= is required)

**Comment by briangig** [comment]
Thanks, it sounds like we have everything set properly, I never see CW reach out to the server in the access logs so the issue must be on CW.  This is on v2018_3, should still work afaik.  Seeing if CW support has nay ideas.
