### ISSUE TITLE
Anyway to handle branch changes?

### ISSUE THREAD

**Issue by briangig** [jundis/CWSlack-SlashCommands#129]
Going from 2018_3 to 2018_4 (hosted) broke the new ticket slash command (everything else seemed to keep working), until I updated the config.php variable.  Is that the only way to resolve moving forward?

**Comment by jundis** [comment]
You can set the branch as v4_6_release and it should work through upgrades.

**Comment by briangig** [comment]
Seems to work!  Thanks!

**Comment by JasonUnger** [comment]
Didn't think to check closed tickets. I'll give that a try in the morning.
