### ISSUE TITLE
Tracking of cloud version

### ISSUE THREAD

**Issue by JasonUnger** [jundis/CWSlack-SlashCommands#130]
Hello, we are using the cloud version of connectwise, and every time they update our instance, I need to go in and update the config file with the new directory name.

Can this be patched to work?

Additionally, could the bug where the "Ticket #nnnn has been created by ." doesn't include any name be fixed?

**Comment by briangig** [comment]
Does #129 fix your version change issue?

**Comment by JasonUnger** [comment]
Didn't think to check closed tickets. I'll give that a try in the morning!

**Comment by jundis** [comment]
Sorry, I totally missed this happening.

Changing to v4_6_release should definitely work. Could you expand on your issue with the Ticket has been created by, does it never show the name or does it only show it for certain tickets?

**Comment by JasonUnger** [comment]
Hi, switching that did work.

The issue with the names only happens on some tickets. I haven't looked to find a pattern.

**Comment by jundis** [comment]
If you could let me know if you see any sort of pattern, I can definitely take a look at it. You're the first to report this issue and I can't say I've ever seen it in our own Slack teams.
