### ISSUE TITLE
No longer able to create tickets

### ISSUE THREAD

**Issue by briangig** [jundis/CWSlack-SlashCommands#132]
We've had this running for a while, we are using hosted CW and it seems we are no longer able to create tickets.  Enabling debug gives me:

`</pre>Unknown Error Occurred, check API key and other API settings. Error ConnectWiseApi: Could not find member 'enteredBy' on object of type 'Ticket'. Path 'enteredBy', line 1, position 51.Check your accept header to make sure you are using the correct version.`

Our CW name and Slack names match, but I did try and use the internal DB to map myself, and that did not resolve the issue.

**Comment by kenoyer130** [comment]
Hi Jundis/Cwslack-Slashcommands, we recently moved the EnteredBy from the
main body of the ticket to the meta data to standardize its location with
the other endpoints. This was documented as a breaking change but many
people missed it.

**Comment by jundis** [comment]
Brian, I'm working on updating this here and I should have a new copy up by the end of the weekend.

**Comment by jundis** [comment]
Brian,

Please update to the latest files. Note you need to set the $cwClientId variable in config.php to your clientId value, you can retrieve this from the CW Developer team at https://developer.connectwise.com

Let me know if that fixes your issues.

**Comment by briangig** [comment]
Thanks, will try and get back to you!

**Comment by briangig** [comment]
Finally got time to update, worked like a charm, thanks!
