### ISSUE TITLE
All integration will need a valid clientID in the next month or two

### ISSUE THREAD

**Issue by kenoyer130** [jundis/CWSlack-SlashCommands#133]
@jundis be aware ConnectWise will be soon in the next month or two be rejecting any Rest API calls without a valid client id as outlined here :

https://developer.connectwise.com/Products/Manage/Developer_Guide

So be sure to update your integration!

Note this will only affect versions 2018.3 and above and might be postponed to 2018.4.

**Comment by jundis** [comment]
Thanks for the reminder! I had updated mspIC but not this yet. I'll get one pushed out here in the next few days.

**Comment by jundis** [comment]
Kenoyer,

Just to clarify here, are you expecting all ConnectWise partners who want to use an open source integration like this to register as developers, or is there another method of acquiring a clientID value? I just need to know to update my documentation on if people need to do that.

Thanks
