### ISSUE TITLE
Expand feature set beyond Slack

### ISSUE THREAD

**Issue by therealscottcarlow** [jundis/CWSlack-SlashCommands#14]
This project seems relatively easily portable for use with other services that use a REST API, two services of particular interest, in my mind, are Office Planner and Trello. Half of the leg work is already done via facilitating HTTP requests to Connectwise and returning the JSON object. 

Integrations such as these eliminate the need for tools like Kanbanize.com to bring Agile methodologies to the Connectwise PSA and would put forth a lot of value.

**Comment by jundis** [comment]
@therealscottcarlow, how do you envision this used by Trello and Office Planner? I could definitely delve into the details of their APIs and setup Connectwise to work with them in some way, I just don't use these products so I'm not sure exactly what should be done with them to make everything easier.

Thanks for the suggestion!

**Comment by therealscottcarlow** [comment]
Sign up for a free trello account. Make a board, and name each column, often called "Swim Lanes" in Agile lingo, after the common ticket statuses you use in your CW tenant. This is the basic workflow. Planner works much in the same way, but they call their columns "buckets". For Planner, the Microsoft Graph API for Tasks is what you use. Moving cards between lanes can trigger stasis changes, notes made on the Trello or Planner cards could be synced to the ticket, you can add time to the card,  etc and it will update the ticket. 

Likewise, tickets on a board or attached to a resource can create cards in Trello/Planner according to ticket status, which will auto-populate columns, and updates to the ticket updates the card.

That's my vision at least, and people managed to pull it off via Kanbanize.com, so I imagine similar features can be inote grated into other platforms provided a robust enough API, which a casual perusal of the Tasks API has me confident that at least Planner integration could work.

I haven't had much time to start trying to hack it out, or else I would have sent you some PR's by now.

**Comment by therealscottcarlow** [comment]
Oh, also, I realized that you might want to keep this repo CW-Slack only. If that's the case and you make another repo for other integrations, I'll move my issue there. Not trying to clutter up your issues. :)

**Comment by jundis** [comment]
Still tracking, haven't had time to look into Trello or other products really.

**Comment by jvanschaack** [comment]
I would suggest a work around for this.   This is only 1 service and there might be others but https://sameroom.io/  allows you to link different chat/collaboration programs.

**Comment by jundis** [comment]
@Infested that wouldn't work for any other chat integration, as Slack only allows slash commands inside Slack from what I've seen. So /t 51373 in IRC would just output that as text to Slack.

**Comment by jvanschaack** [comment]
Hrm,  I thought bots could invoke them.  oh well.  it would still be able to broadcast outward however.

**Comment by therealscottcarlow** [comment]
In theory a bot could facilitate that, if I understand the proposal
correctly, but that would be a completely different project than this one.

**Comment by jundis** [comment]
At this point I'm going to close this ticket as won't fix. In the future I may revisit it but I just don't have time at the moment to spend on other projects.
