### ISSUE TITLE
"Latest note" from follow updates is not always the latest note

### ISSUE THREAD

**Issue by jundis** [jundis/CWSlack-SlashCommands#18]
From internal discussion.

The "latest note" field in incoming updates does not always appear to show the latest note. Appears to possibly be an issue with the API as calls to /notes?orderBy=id%20desc do not show latest note.

**Comment by kenoyer130** [comment]
If you get me reproducible steps I can log a ticket with the API team. Also what version of ConnectWise are you running against.

**Comment by jundis** [comment]
@kenoyer130:

It appears to happen to some, but not all tickets. One of the ones that I've noticed this on has 90 notes, and the latest one that shows even with a pageSize set to 100, is from 3 notes ago. Verified it is not internal or external specific.
1. Login to ConnectWise
2. Open https://cw.domain.com/v4_6_release/apis/3.0/service/tickets/TICKETNUMBER/notes?orderBy=dateCreated%20desc
3. Verify latest note listed in CW is not listed on API page.

Currently experiencing this on:  v2016.4 (41139)

**Comment by kenoyer130** [comment]
Response >

are you referring to the order of the notes pod in ConnectWise UI?
because that is composed of more than just notes... it also includes Time Entries
so I'm thinking the "missing" notes he is referring to are time entry record notes, because those are not available in the /tickets/{id}/notes endpoint

**Comment by kenoyer130** [comment]
assuming that is the issue

https://{connectwiseSite}/v4_6_release/apis/3.0/time/entries?conditions=chargeToId={ticketId}&chargeToType={ServiceTicket,ProjectTicket,etc}

ex: http://10.30.1.22/v4_6_development/apis/3.0/time/entries?conditions=chargeToId=1344&chargeToType='ServiceTicket'

if he just wants the notes for each time entry, do something like this `http://10.30.1.22/v4_6_development/apis/3.0/time/entries?conditions=chargeToId=1344&chargeToType='ServiceTicket'&fields=notes`

We are discussing the possibility of changing the api to include both in the future.

**Comment by kenoyer130** [comment]
And as always
--> Standard Disclaimer <-- 
Opinions expressed are solely my own and do not express the views or opinions of ConnectWise.

**Comment by jundis** [comment]
@kenoyer130 
That is definitely where the issue lies. I had mistakenly figured that the TicketNotes portion of the API would include just the note parts of time entries.

I'll have to run API connections to both /time/entries and /service/tickets then with a date comparison to see which is the latest "note" on the ticket.

I would definitely put a +1 on changing that to include both in future modifications to the API.

Thanks for the help on this!

**Comment by kenoyer130** [comment]
An enhancement ticket has been put in with the API team.

**Comment by jundis** [comment]
Fixed with commits 82cf3c9, 1b42487, and b98b62f

Thanks to @kenoyer130 for the assistance!
