### ISSUE TITLE
Text appears "below the fold"

### ISSUE THREAD

**Issue by jundis** [jundis/CWSlack-SlashCommands#2]
Per: https://www.reddit.com/r/msp/comments/4v8skr/connectwiseslack_api_integration_xpost/d5wscpx?context=3

**Comment by jundis** [comment]
Support request submitted to Slack.

**Comment by jundis** [comment]
Working with Slack support, sounds like it may be a bug with the client itself. Waiting to hear back.

**Comment by jundis** [comment]
Sent request for update to Slack support.

**Comment by jundis** [comment]
Slack still has not resolved this issue. Pushing off to 1.6 release and hopefully they will get back to me on it by then.

**Comment by jundis** [comment]
Removing milestone, not sure when Slack support will get to this.

**Comment by jundis** [comment]
Still no reply from Slack support. Most likely a WNF by them it seems.

**Comment by briangig** [comment]
For whats its worth, I have seen the same behavior in other integrations - so I is definitely not a bug or issue related to your code.

**Comment by jundis** [comment]
Closing as wontfix. No point keeping this issue open when there has been nothing done on Slack's end to resolve.
