### ISSUE TITLE
Calling a contract results in error with markdown text, but pulls the contact

### ISSUE THREAD

**Issue by jdubose9** [jundis/CWSlack-SlashCommands#30]
I've updated to 1.6 and the cw-contact seems to not be working on my system, but I'm sure it's just a misconfiguration on my end somewhere. When I perform "/cwcontacts Smith", I get the follow returned:

```
<br />
<b>Notice</b>:  Undefined property: stdClass::$communicationItems in <b>/var/www/html/cwslack-contacts.php</b> on line <b>100</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/html/cwslack-contacts.php</b> on line <b>104</b><br />
<br />
<b>Notice</b>:  Undefined property: stdClass::$name in <b>/var/www/html/cwslack-contacts.php</b> on line <b>115</b><br />
{
   "parse": "full",
   "response_type": "in_channel",
   "attachments": [
       {
           "fallback": "Contact Info for John Smith",
           "title": "Company: ",
           "pretext": "Contact Info for John Smith",
           "text": "",
           "mrkdwn_in": [
               "text",
               "pretext"
           ]
       }
   ]
}
```

**Comment by jundis** [comment]
Do you have any other parts of the repo working? Such as the main cwslack.php

**Comment by jdubose9** [comment]
Parts of it are working. We can see ticket entries being entered (although I think that's cw-incoming) and we can retrieve ticket information and see some notes. We're using all modules in CWSlack, it's just this feature that seems to be giving the most issues.

**Comment by jundis** [comment]
What version of ConnectWise are you running?

Also, please add the following line to line 91 after "$dataTData = json_decode($curlBodyTData); //Decode the JSON returned by the CW API."

`var_dump($answerTData);`

Let me know what you get for output with that line there.

**Comment by jundis** [comment]
@jdubose9 have you had a chance to run this with the var_dump line added?

**Comment by jundis** [comment]
Fixed in latest commit.
