### ISSUE TITLE
Allow wildcard in config search

### ISSUE THREAD

**Issue by briangig** [jundis/CWSlack-SlashCommands#33]
We use configurations in CW that pull data on endpoints from Kaseya.  I have modified our cwslack-config.php to pull in the data, including model, warranty, etc.  Is there anyway to do a wildcard search in configs? Or at least search all configurations based on the name?  I am looking through the code now but I am not as versed in CW.

for example, instead of having to type out /config name of client here|server123FS.root.cnd, I'd like to be able to type /config server12\* and still allow the config to be found.

**Comment by briangig** [comment]
After some messing around I am not sure if 'wildcards' in the sense I want is possible, but I was able to search all configurations (it was actually easier than I thought) by just eliminating the company field from the search.  I also modified the url to only return active configurations (I was trying to figure out why old random machines were being returned that I couldn't find in CW manually).

```
// $company=NULL; //Just in case
$config=NULL; //Just in case
$config = $exploded[0]; //We only need to grab the config name now

$url = $connectwise . "/v4_6_release/apis/3.0/company/configurations?conditions=status/name=%27active%27%20and%20name%20contains%20%27" . $config . "%27&pagesize=1";
$url = str_replace(' ', '%20', $url);; //Encode URL to prevent errors with spaces.

```

So now I can at least return a config if the first x amount of characters are unique, so "/config server123" would return server123FS.root.cnd as long as there were no other matches.  I can specify deeper by adding more characters, \* does not seem to be needed.

**Comment by briangig** [comment]
Also, if I'm sure you have access to this, (I only found it in the developer forums), if you want to return a link to the configuration in the response, the url is
`
/v4_6_release/services/system_io/router/openrecord.rails?locale=en_US&recordType=ConfigFv&recid=
`

**Comment by jundis** [comment]
I'll put a catch in for singular searches that don't include company name. Good idea on the link too
