### ISSUE TITLE
Allow /note command to send e-mails based on internal/external status.

### ISSUE THREAD

**Issue by jundis** [jundis/CWSlack-SlashCommands#40]
Internal request.

Need to have the /note command be able to e-mail clients with external status. Set optional with possibly an e-mail function?

Not even sure if the API allows for e-mailing with notes.

**Comment by jundis** [comment]
@kenoyer130 is this possible?

**Comment by kenoyer130** [comment]
"I am pretty sure for per note processing of notifications you need to pass the /note request with the processNotifications property set to true

"I think if you want all of the notes attached to the ticket to be processed by default, you set the processNotifications property to true on the Ticket object

and each subsequent note/time entry request will automatically be processed"

**Comment by jundis** [comment]
@kenoyer130 That worked great for external notes. When I use processNotifications on internal notes however, it still e-mails the contact on the ticket. Is that a limitation of how the API works?

**Comment by jundis** [comment]
Closing as completed. External e-mail is good enough, no real need to use internalemail as you can just ping the person on slack really..
