### ISSUE TITLE
CWSlack-Incoming: Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by pharismod** [jundis/CWSlack-SlashCommands#41]
I'm getting the following when I browse to cwslack-incoming.php and new tickets aren't being posted.

Notice: Trying to get property of non-object in D:\home\site\wwwroot\cwslack\cwslack-incoming.php on line 29

**Comment by jundis** [comment]
That's expected, browsing to it will fail, just forgot to add a catch for that.

Besides that, do you have $posttext set to 1? If so set it to 0 and let me know if you still have issues with new tickets not posting.

**Comment by pharismod** [comment]
Done, but still not working...

I tried manually created tickets as well as tickets via the email connector. I also deleted the webhook and created a new one.

**Comment by jundis** [comment]
Any error when visiting the cwslack-incoming.php page manually?

Sorry for delay in response

**Comment by jundis** [comment]
The only thing I can think of is it may be that you don't have an initial note on the ticket? I noticed that for my tickets, anything that doesn't have a note in it fails which I need to fix.

You can try doing a manual curl to the cwslack-incoming.php if you're comfortable with that and have a linux box available. Not sure how to do it in windows

**Comment by pharismod** [comment]
Hey,

So I noticed that it started working this morning for some tickets. It appears to be working for tickets that we create manually. Emailed tickets do not work.

In both cases, the ticket has an entry in the Discussion tab but not the Internal tab.

**Comment by jundis** [comment]
Add these lines at the top of cwslack-incoming.php, changing the second one to a spot that the PHP system can write to for errors.

```
ini_set("log_errors", 1);
ini_set("error_log", "/tmp/php-error.log");
```

Then test the e-mail tickets and it should output errors to that php-error.log file. Once you've got an error or two, upload it here so I can take a look.

**Comment by pharismod** [comment]
I seem to be having no luck getting anything to write to the log file... any other ways to get this information?

**Comment by jundis** [comment]
May be due to the display_errors being set to 1 in all cwslack files.

Try removing that line per: http://www.cyberciti.biz/tips/php-howto-turn-on-error-log-file.html

**Comment by jundis** [comment]
@pharismod Try this from a linux shell if you can:

curl -d @data.txt -iv --raw -H "Content-Type: application/json"  "https://yoururl.com/cwslack-incoming.php?id=545137&action=added&srDetailRecId=1002946&timeRecId=0&srtServiceRecId=0&memberId=techname&notes=&isProblemDescription=True&isInternalAnalysis=False&isResolution=False"

And have data.txt be:

```
{
  "FromUrl": "cw.you.com",
  "CompanyId": "company",
  "MemberId": "test",
  "Action": "updated",
  "Type": "ticket",
  "ID": 538974,
  "Entity": "{\"Id\":538974,\"CompanyName\":\"Client\",\"CompanyId\":217,\"ContactId\":225,\"ContactName\":\"User Name\",\"AddressLine1\":\"481 Address Lane\",\"AddressLine2\":\"\",\"City\":\"City\",\"StateIdentifier\":\"State\",\"Zip\":\"24993\",\"Country\":null,\"BoardName\":\"Not\",\"BoardId\":10,\"TicketStatus\":\"Need to Schedule\",\"StatusName\":\"Need to Schedule\",\"ClosedFlag\":false,\"Type\":\"MUST CHANGE\",\"SubType\":null,\"SubTypeItem\":null,\"Priority\":\"Moderate (work around / use another system)\",\"Location\":\"In-house\",\"Source\":\"Phone\",\"Summary\":\"Perf - Total CPU Processor Time:602517 - Error\",\"EnteredDateUTC\":\"2016-08-05T20:53:43.773\",\"LastUpdatedUTC\":\"2016-08-05T20:53:44.127\",\"Resources\":null,\"RequiredDateUTC\":null,\"ClosedDateUTC\":null,\"SiteName\":\"Main office\",\"BudgetHours\":0.00,\"ActualHours\":null,\"Approved\":true,\"ClosedBy\":null,\"ResolveMins\":0,\"ResPlanMins\":0,\"RespondMins\":0,\"UpdatedBy\":\"LabTechInt\",\"RecordType\":\"S\",\"TeamId\":34,\"AgreementId\":40,\"Severity\":\"Low\",\"Impact\":\"Medium\",\"DateResolvedUTC\":null,\"DateResplanUTC\":null,\"DateRespondedUTC\":null,\"ContactEmailAddress\":\"test@test.com\",\"ContactPhoneNumber\":\"328428348\",\"IsInSla\":true,\"StatusId\":162}",
  "Metadata": null
}
```

**Comment by jundis** [comment]
Closing as no-response. Please re-open if you have a chance to test above and need help further.
