### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by shortcutshawn** [jundis/CWSlack-SlashCommands#45]
I'm getting the following error:

<b>Parse error</b>:  syntax error, unexpected '**APIKEYSHOWNHERE***' (T_STRING) in <b>/var/www/html/CW/config.php</b> on line <b>27</b><br />

Is this an API configuration error, or a webserver issue ?

Appreciate any advice.

**Comment by shortcutshawn** [comment]
Ok, MacOS decided to change all the " in the config.php, after resolving this, i now get : 

# 

# Array not returned in line 195. Please check your connectwise URL variable in config.php and ensure it is accessible via the web at https://za.myconnectwise.net/v4_6_release/apis/3.0/service/tickets/1301772

My CW url is https://za.myconnectwise.net

Any ideas ?

**Comment by jundis** [comment]
Change the url to https://za-api.myconnectwise.net

Hosted ConnectWise has a different URL for API access

**Comment by jundis** [comment]
Sorry, that should be api-za not za-api

**Comment by shortcutshawn** [comment]
Sorted, thanks!
