### ISSUE TITLE
Slack follow links from ConnectWise 

### ISSUE THREAD

**Issue by adamhancock** [jundis/CWSlack-SlashCommands#60]
Really good job on the integration. Just updated to the latest version with the MySQL DB. 

I found that the Slack follow links from inside Connectwise still entered the connectwise username in the follow table. 

I updated line 66 of cwslack-follow.php from
`$username = $_GET['memberid'];`

 to this: 

$mysql = mysqli_connect($dbhost, $dbusername, $dbpassword, $dbdatabase); 
    if (!$mysql) //Check for errors
        {
        die("Connection Error: " . mysqli_connect_error());
        }
    $sql = "SELECT slackuser FROM usermap where cwname = '".$_GET['memberid']."'"; 
    $result = mysqli_query($mysql, $sql); //Run result
    # Check for mapping, otherwise use Connectwise 
    if(mysqli_num_rows($result) > 0){
    $user = mysqli_fetch_assoc($result);
    $username = $user['slackuser']; 
    }else{
    $username = $_GET['memberid'];
    }

It then maps to right user.

**Comment by jundis** [comment]
Woooooooooooops!
