### ISSUE TITLE
Slash command for /t not displaying correctly

### ISSUE THREAD

**Issue by digitalbydesign** [jundis/CWSlack-SlashCommands#62]
I followed the instructions to the letter and it does appear to actually pull the ticket but the formatting is all wrong as all I see is the HTML formatting code along with the ticket information. Any help/guidance would be greatly appreciated!
![image](https://cloud.githubusercontent.com/assets/9658839/19928282/76675846-a0c3-11e6-99ff-f786b70439a2.png)

**Comment by jundis** [comment]
Timezone is incorrect here it seems. America/Arizona is not a valid timezone.

Change line 29 of config.php from "America/Arizona" to "America/Phoenix" and let me know if you're still having issues.

**Comment by digitalbydesign** [comment]
Excellent response time! That seems to have done the trick, but now I'm getting a 'Timeout was reached' about 50% of the time when attempting to use the /t slash command. Seems to be when I'm trying to pull a ticket that is fairly old. Any ideas on that?

**Comment by jundis** [comment]
That's all about database/connection speed. Slack has a timeout duration of 3 seconds, so if you go to https://cw.<you>.com/v4_6_release/apis/3.0/service/tickets/<ticket number> and it takes more than a second to load, you're going to have issues since it calls that link a number of times.

One workaround may be to set $posttext to 0 in config.php line 62. This will drastically reduce the amount of calls to the ConnectWise API, but also will no longer show ticket notes in response to /t

**Comment by digitalbydesign** [comment]
That's understandable. I assume this is the database/connection speed coming from the webserver hosting CWSlack? I'm running this from a fresh droplet on Digital Ocean's servers (ubuntu 16.04). Any tips on increasing the database speed as I KNOW their connections are top notch. Again, very much appreciate the prompt feedback!

**Comment by digitalbydesign** [comment]
Changing $posttext to 0 allowed old tickets to be pulled using /t so much appreciated. I know management really liked the ability to see the latest notes so looks like I'll need to troubleshoot/optimize the MySQL db some to get this functionality back.

**Comment by jundis** [comment]
The bottleneck is usually between the script and the ConnectWise database itself.

So visiting the API URL above for an older ticket, like https://cw.something.com/v4_6_release/apis/3.0/service/tickets/100, needs to be able to pull up within 1 second or so. Compare that to visiting a new ticket like https://cw.something.com/v4_6_release/apis/3.0/service/tickets/100000, or wherever your new ticket numbers are at, and see if there is a speed difference.

If so, then yea the bottle neck is on the ConnectWise database trying to pull older data. 

You can try splitting it if you wanted if you can find a reasonable point. Add this to line 177 of cwslack.php before if($posttext==1)

`if($ticketnumber<100000)
{
    $posttext=0;
}`

Set 100,000 to whatever number you determine the issue stops at, and it should allow for new tickets to have notes posted while older tickets do not.

**Comment by digitalbydesign** [comment]
Brilliant idea sir, now to take the time and figure out roughly where the bottleneck occurs on our older tickets. Appreciate all your help today.

**Comment by jundis** [comment]
Not a problem, that's what I'm here for!
