### ISSUE TITLE
Reply to tickets with closed loop time entry

### ISSUE THREAD

**Issue by ponchohoncho** [jundis/CWSlack-SlashCommands#63]
Could it be possible to /reply to a ticket in slack and have it generate a closed loop time entry with X minutes on it to send an email back to the user? bonus points for setting the ticket's status to "waiting for client response". extra bonus points for supporting discussion/internal/resolution flags somehow and closing the ticket on resolution?

/reply 102345 d 5m No problem, are you seeing this issue only on local files or also network files?
/reply 102345 i 1.5h Remote session with user to determine that files were deleted 3 months ago.
/reply 102345 dr 5m As per our phone conversation, we restored the files from the backup. Please let us know if you have any further issues.

**Comment by jundis** [comment]
Probably can roll this into /note without much fuss. May need to break it off but we'll see.

**Comment by jundis** [comment]
Separate module cwslack-time, related request: #29 

Command: /time [ticket number] [type] [time] [note]

Accepted Values
[ticket]: integer (e.x. 123456)
[type]: detail/internal/resolution or d/i/r
[time]: integer type, no spaces (e.x. 5m, 1.5h)
[note]: text

Variables:
$slacktimetoken = slack token
$statusresolution = completed resolution status.
$statusdetail = waiting on client status

**Comment by cjvanderlinden** [comment]
Not great at reading the code yet - but getting this error with /time

> Unknown Error Occurred, check API key and other API settings. Error: InvalidObject

**Comment by jundis** [comment]
Yea /time isn't done yet haha. Haven't had time to work on it @cjvanderlinden.

Soon!

**Comment by cjvanderlinden** [comment]
Once I wrap my brain around coding again (been way too long!) maybe i'll be
able to do some merge requests.  Not knowing PHP will be a problem as well.

**Comment by jundis** [comment]
Completed code for this. No longer changes statuses after time entry is submitted because I can't make it properly process notifications for this.

Please feel free to test it out @cjvanderlinden and @ponchohoncho. I'll finish readme documentation and the rest of the stuff before 2.1 release.

**Comment by jundis** [comment]
Completed.
