### ISSUE TITLE
Web Hook

### ISSUE THREAD

**Issue by jvanschaack** [jundis/CWSlack-SlashCommands#65]
Is there a way to configure multiple incoming hooks?

We have 2 different boards that I am trying to get to go to seperate channels.  IS this supported and if so what is the proper way to set this?

**Comment by jundis** [comment]
@Infested: One way of doing this would be to copy the cwslack-incoming.php, functions.php, and config.php file into a new folder on your web server.

Once there, modify config.php's variable $webhookurl to your new web hook address in Slack for your second channel.

You will then need to create a new CW integration on the Integrator setup table, and set the callback up with your second board, pointing to http://yourdomain.tld/subfolder/cwslack-incoming.php?id=

**Comment by jvanschaack** [comment]
I thought about doing this.  I will do this for now thanks for the fast reply.

I guess the next question is can we do a feature request for this to be included inside the setup or even a way to do it in the config manually.  I'm sure I am not the only one that might need this.

**Comment by jundis** [comment]
Tagged. I'll get to it sometime this week.

**Comment by jundis** [comment]
@Infested Please try this out, let me know if it works for you. Need to document it fully still, but use this for your callback URL and get back to me.

https://yourdomain.tld/cwslack-incoming.php?channel=CHANNELNAME&board=BOARDNAME&id=

You'll need an integrator for each board this way. So if you have 3 boards running to a #tickets channel, you need a integrator with callback for each board, specifying that channel.

**Comment by jundis** [comment]
Download the latest cwslack-incoming.php of course

**Comment by jvanschaack** [comment]
Sorry I was unavailable for a few.  I am going to try this now. 

One added question that maybe I am setting up wrong.   Is there a way to set the incoming on the board for all tickets created?   It seems that only tickets created by users are sending to slack, not the ones sent in from clients with no one assigned.

**Comment by jvanschaack** [comment]
Just to add.  The new updates work great.  Thank you.  
However I am unsure about the unassigned tickets created through email connector.  I have tested both catchall and non catch all style tickets.  Both are ignored.

**Comment by jundis** [comment]
Make sure that the variable $allowzadmin is set to 1 in config.php. Line 67 it should be

**Comment by jvanschaack** [comment]
Wow.  Can't believe I missed that setting.  Sorry for the dumb issue.  

Everything is working good now.  Thank you.   I will hang around and help others that post if I can.

**Comment by jundis** [comment]
Not a problem!

Closing as resolved. 2.1 release will go out today.
