### ISSUE TITLE
Question on feature

### ISSUE THREAD

**Issue by jvanschaack** [jundis/CWSlack-SlashCommands#70]
Was wondering if this script took  environmental variables.    This would make it compatible with like Heroku or Scalingo ect.   Easy github integrated deployments.

**Comment by jundis** [comment]
I'll look into this.

**Comment by jundis** [comment]
Closing as won't fix unfortunately. Not comfortable enough with heroku myself to figure this out and I don't want to make the config.php file extremely convoluted.

If I ever learn how this stuff works I'll spin it off into its own branch most likely.
