### ISSUE TITLE
html returned to slack after creating an activity or querying a contact

### ISSUE THREAD

**Issue by chrisrwebb** [jundis/CWSlack-SlashCommands#72]
Hey,

First of all thanks for doing this!!! I have noticed that if I create an activity or query a contact HTML markup is returned to slack. I presume that is not what is supposed to happen. Can you help me out with this? I have attached a screenshot.

Thanks 

Chris

![image](https://cloud.githubusercontent.com/assets/17365800/21029196/90f89566-bd66-11e6-9519-c2201db95d41.png)

**Comment by jvanschaack** [comment]
Looks like the settings are not right. Double check all your keys and such.

**Comment by chrisrwebb** [comment]
The task gets created and for the contact search a contact is returned. Would that be the keys?

CW

**Comment by jundis** [comment]
Looks like something in your config.php is incorrect, or somehow a quotation mark got broken. Check line 53 of config.php. You can copy+paste it to http://phpcodechecker.com/ and see if it returns any errors. If so, post them here.

If everything looks correct, please put the full HTML output (feel free to sanitize any client details) here and I'll take a further look at it.

**Comment by chrisrwebb** [comment]
OK I got it fixed there was a $ in the DB password. Changed it to ‘ instead of “ and it is all good. Thanks for your help

CW

**Comment by jundis** [comment]
Gotcha.

Sorry about that D:

**Comment by chrisrwebb** [comment]
Could I ask you one other question? For incoming stuff from connect wise does it only notify on tickets with new status? When I create a ticket in Connectwise we get the notification on the channel. However when an email comes in via the email connector there is no notification in slack.

I wondered if the ticket status has to be new.

Thanks,

Chris

**Comment by jundis** [comment]
$allowzadmin in your config.php has to be set to 1 instead of 0, that should solve that. Keep in mind that $postupdated should be set to 0 while this is turned on or your slack will explode.

Let me know if that works for you.
