### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by dmcearchern** [jundis/CWSlack-SlashCommands#74]
I have setup the /contact slash command but when I run it I am getting the below error. I have the ticket integration working normally but cannot seem to get the /contact integration to work. I am using CW SAAS (hosted)

Unknown Error Occurred, check API key and other API settings. Error: Security

**Comment by jundis** [comment]
You'll need to go into functions.php and add the following to line 53:

var_dump($answerTData);

Copy+Paste the response in reply to this issue and we can determine what the issue is.

You'll want to remove that line almost immediately once you get the debug info. It will turn on full logging for all slash commands and incoming webhooks.

**Comment by dmcearchern** [comment]
Looks like SSL is required?

string(2346) "HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 13 Dec 2016 22:59:01 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Content-Length: 2091
Connection: keep-alive

[{"id":2483,"firstName":"Dustin","lastName":"McEarchern","type":null,"company":{"id":2,"identifier":"PRO","name":"ProTechnical Corporation","_info":{"company_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/companies/2"}},"site":{"id":136,"name":"Headquarters","_info":{"site_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/companies/2/sites/136"}},"addressLine1":null,"addressLine2":null,"city":null,"state":null,"zip":null,"country":null,"relationship":{"id":0,"name":"","_info":{"relationship_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/contacts/relationships/0"}},"department":null,"inactiveFlag":false,"defaultMergeContactId":null,"securityIdentifier":null,"managerContactId":null,"assistantContactId":null,"title":null,"school":null,"nickName":null,"marriedFlag":false,"childrenFlag":false,"significantOther":null,"portalPassword":null,"portalSecurityLevel":null,"disablePortalLoginFlag":null,"unsubscribeFlag":null,"gender":null,"birthDay":null,"anniversary":null,"presence":null,"mobileGuid":"de4e7210-5982-4756-bee7-83bb47e37999","facebookUrl":null,"twitterUrl":null,"linkedInUrl":null,"defaultBillingFlag":false,"communicationItems":[{"id":3963,"type":{"id":4,"name":"Cell","_info":null},"value":"5038471076","extension":null,"defaultFlag":true,"communicationType":"Phone"},{"id":3964,"type":{"id":1,"name":"Email","_info":null},"value":"dmcearchern@protechnical.com","extension":null,"defaultFlag":true,"communicationType":"Email"}],"_info":{"lastUpdated":"2016-08-11T15:48:17Z","updatedBy":"CServ","communications_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/contacts/2483/communications","notes_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/contacts/2483/notes","tracks_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/contacts/2483/tracks","portalSecurity_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/contacts/2483/portalSecurity","image_href":"https://na.myconnectwise.net/v2017_1/apis/3.0/company/contacts/2483/image?lastModified=2016-08-11T15:48:17Z"},"customFields":null}]"
string(612) "HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: private
Date: Tue, 13 Dec 2016 22:58:38 GMT
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
x-cw-request-id: 97a431cc-1a67-4732-a205-61f9119ebf3c
X-Powered-By: ASP.NET
x-server-name: IP-0A0A0284
Age: 24
X-Cache: Error from cloudfront
Via: 1.1 437acf5020e44b923e28b10f7fccb788.cloudfront.net (CloudFront)
X-Amz-Cf-Id: rcN6VQqWQBP22Dv7goEKg_KZ038273TQR5ePTNQFLJ66f2ZHuaWq4A==

{
 "code": "Security",
 "message": "SSL is required.",
 "errors": null
}"
Unknown Error Occurred, check API key and other API settings. Error: Security

**Comment by dmcearchern** [comment]
I had to change /v4_6_release to /v2017_1 and now it is working

**Comment by jundis** [comment]
Ah. Yea I'm going to need to fix that. Waiting for 2017_1 to hit GA so I can install and verify what needs changing.

**Comment by dmcearchern** [comment]
Thank you for the quick reply earlier. The Slack integration is incredible.

Dustin McEarchern
support@protechnical.com<mailto:support@protechnical.com>

[sig_logo]<http://www.protechnical.com/>
11575 SW Pacific Highway, Unit 224, Tigard, OR 97223
o: 503.676.3777  |  f: 775.201.0317  |  www.protechnical.com<http://www.protechnical.com/>
