### ISSUE TITLE
NO FALLBACK DEFINED

### ISSUE THREAD

**Issue by briangig** [jundis/CWSlack-SlashCommands#8]
Hi,

In the Slack notification, NO FALLBACK DEFINED is displayed.  If I can figure out how to pull/push whatever to Github I will, but the fix is to add:

`"fallback" => "Info on Ticket #" . $dataTData->id,`

to the first line of each attachment in the array:

`$return =array(
        "parse" => "full",
        "response_type" => "in_channel",
        "attachments"=>array(array(
            "fallback" => "Info on Ticket #" . $dataTData->id, //Return info string with ticket number.
            "title" => "<" . $ticketurl . $dataTData -> id . "&companyName=" . $companyname . "|#" . $dataTData->id . ">: " . $dataTData->summary, //Return clickable link to ticket with ticket summary.
            "pretext" => "Info on Ticket #" . $dataTData->id, //Return info string with ticket number.
            "text" =>  $dataTData->company->identifier . " / " . $contact . //Return "Company / Contact" string
            "\n" . $dateformat . " | " . $dataTData->status->name . //Return "Date Entered / Status" string
            "\n" . $dataTData->resources, //Return assigned resources
            "mrkdwn_in" => array(
                "text",
                "pretext"
                )
            ))
        );
}`

I guess you could add whatever you wanted, I only wanted the Ticket #

**Comment by briangig** [comment]
This is a little better: http://pastebin.com/uyBssy56

I am not using the status or other commands yet, but I assume the same fix will work.

**Comment by jundis** [comment]
Fixed in the latest commit 01611e7ada1b586cf8753b50716606fde5f35cc7
