### ISSUE TITLE
Company names in /t

### ISSUE THREAD

**Issue by maddog986** [jundis/CWSlack-SlashCommands#88]
Company names with spaces errors out the curl function in functions.php

Example command: /t new onsite|buisness name|testing schedule
Results in errors: Warning</b>:  array_key_exists() expects parameter 2 to be array, null given in 
functions.php on line 54

Strings need to be wrapped with urlencode in cwslack.php (line 92). Example:

`$companyurl = $connectwise . "/v4_6_release/apis/3.0/company/companies?conditions=name%20contains%20%27" . $ticketstuff[1] . "%27";`

replace with:

`$companyurl = $connectwise . "/v4_6_release/apis/3.0/company/companies?conditions=name%20contains%20%27" . urlencode($ticketstuff[1]) . "%27";`

Probably more strings need to be updated but this one i found today.

**Comment by jundis** [comment]
Fixed this one, not seeing any others that should cause issues.
