### ISSUE TITLE
Timeout was reached

### ISSUE THREAD

**Issue by maddog986** [jundis/CWSlack-SlashCommands#89]
Slack has a strict 3000ms response rule. Sometimes when requesting ticket information or creating new tickets we get the "slackbot: Darn – that slash command didn't work (error message: `Timeout was reached`)" response.

I guess the only way to avoid this would be to rewrite the code with a simple "OK" 200 return message then use the response_url to send the requested info back to the slack user/channel.

**Comment by jundis** [comment]
Definitely been meaning to take care of this at some point.

Going to be a bit of a rewrite to do so but shouldn't be too bad.

**Comment by jundis** [comment]
@maddog986 Please download the latest files and let me know if you run into any issues or if I can close this as resolved.

**Comment by jundis** [comment]
Would like to go over this once more and turn off the commands showing for previously ephemeral commands.

**Comment by maddog986** [comment]
I will test this today and let you know. Thank you!

edit: No longer getting Timeout Reached but also not getting any response when creating a new ticket.

**Comment by jundis** [comment]
@maddog986 Fixed that I believe. Lots of missing returns on the new ticket function.

**Comment by jundis** [comment]
Closing as resolved.
