### ISSUE TITLE
Put the message body in the ticket notification

### ISSUE THREAD

**Issue by ponchohoncho** [jundis/CWSlack-SlashCommands#9]
I can't be in front of CW all day, so I use the Slack integration mostly to avoid getting a million emails about ticket updates. The updates are a good start, but I'd love to see the message in the alert so I could see what the user has updated with to know if it's something I need to deal with now or can table till later.

**Comment by jundis** [comment]
Completed in Commit 24fd46ec06478b838d1d4b6f5e7e9b36fc4c9a5a
