### ISSUE TITLE
Notify technician of upcoming SLA violation

### ISSUE THREAD

**Issue by briangig** [jundis/CWSlack-SlashCommands#90]
I don't think this exists (I am still using an old version of this), but a great feature would be to send a message to a user when they are x amount of minutes from and SLA violation.

**Comment by jundis** [comment]
If you could clarify exactly what you mean here, that'd be great. We don't leverage the SLA functions of ConnectWise all that much.

**Comment by briangig** [comment]
Well to be honest this is new for us as well!  I am looking into it now, and I think it may work similarly to firmalerts.

For a newly assigned ticket, there is a timestamp that is the SLA time: https://gyazo.com/8f547855e7b05451be9f18a30c56b349

If the SLA time entry was, say 30 minutes away, and the ticket had not been changed, a message should be sent to the user in Slack about an upcoming SLA violation.

**Comment by jundis** [comment]
Mmm unfortunately it looks like the only information I can get from the API is the value "isInSLA" which only returns true or false on whether SLA has passed.

Unfortunately I'm going to have to mark this one as will not fix for now. Should CW ever change it to include the SLA date in the API, we may be able to make this happen. A true/false value however just would not work properly as it would constantly have to alert if it's failed SLA which opens up a slew of other issues.
