### ISSUE TITLE
Issue after upgrade

### ISSUE THREAD

**Issue by jvanschaack** [jundis/CWSlack-SlashCommands#96]
I had putting in issue tickets for something like this but best source of assistance.  

I recently upgraded our code to 2.3 using the upgrades scripts from 2.0.  Since then I cannot get cwslack to work.  Keep returning "Unknown Error Occurred, check API key and other API settings. Error: Security".

The cwslack-incoming is still working so I know the files are right.  I have double checked the API keys as they have not changed but just in case.  

Anything I should look at to try and diagnose this?

**Comment by jundis** [comment]
Resolving via LTG slack

**Comment by jundis** [comment]
Fixed by reconfiguring all scripts

**Comment by dsinton** [comment]
i am having thsi same issue.  what was the fix.  
<br />
<b>Notice</b>:  Undefined property: stdClass::$text in <b>/var/www/html/cwslack.php</b> on line <b>625</b><br />
Unknown Error Occurred, check API key and other API settings. Error ApiFindCondition: Condition Syntax Error (Line 1, Character 9) - Unrecognized value: 4ANDobjectId
String values should be enclosed with double or single quotes; DateTime values should be enclosed in square brackets; numbers should consist of only digits, and optionally a decimal point and a negation sign; boolean values should be indicated with the keywords true or false; null values should be indicated by the keyword null.
