### ISSUE TITLE
Documentation project

### ISSUE THREAD

**Issue by jundis** [jundis/CWSlack-SlashCommands#98]
Need to re-comment all code, and refactor any that is extremely frequently used.

**Comment by djgmog** [comment]
I've just started using this (love it!!!!) but I'm lost on the incoming.php side of it, is there a way to view an error log or better understand why it isn't working (or a better place to post these questions)? Thank you!

**Comment by jundis** [comment]
Closing, documentation and code cleanup will be part of v3 redesign
